version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: aspnet_mariadb
    environment:
      MYSQL_DATABASE: MyAngularAppDb
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: aspnetuser
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mariadb_data: 